### PR TITLE
Merge Users (login) and Employees CRUD

### PR DESCRIPTION
**Pull request by danjohnvelasco**
Continuation of @JohannGon118 PR of employees-crud branch

employee-crud branch have:

- Retrieving from the database
- Adding New Employees
- Update Existing Employees (not working)
- Deleting Existing Employees
- Empty Input Validation
- Specific Validation for Unique Usernames

Changes:

- Fixed Update Existing Employees; includes password hashing
- Added hashing to employee register
- Added confirm password form validation
- All employees can now register

### CODE REVIEW

**Comment by JohannGon118** [comment]
Hashed password gets sent to password when editing

Maybe we can drop the autofill feature and just leave it completely blank

image

**Comment by JohannGon118** [comment]
Duplicate usernames does not display/catch error properly
Can push edits to fix this issue

Sample input: 
username: root

Server throws status 400 
Taken from browser console
```
xhr.js?b50d:177 POST http://localhost:3000/employees/register/ 400 (Bad Request)
```

**Review by JohannGon118 — CHANGES_REQUESTED** [review]
What works:
1. Creating new employees (assuming unique username)
2. Editing Fields except for Password
3. Deleting Employee

What can be improved
1. Password field autofill feature might need to be dropped, meaning fields is empty upon editing an employee (this might mean we have to redevelop how we edit employees to work around the hashed passwords)
2. Add a feature to change Navbar username from 'Rex Lapis' to current users Username

Known issues found: 
1. Validation for non-unique Usernames does not properly display (will push a fix for this)

**Comment by JohannGon118** [comment]
Resolved:
Validation for non-unique Usernames now properly displays

**Comment by danjohnvelasco** [comment]
> 2\. Add a feature to change Navbar username from 'Rex Lapis' to current users Username

Will open a different PR for this feature.

**Comment by danjohnvelasco** [comment]
> * Password field autofill feature might need to be dropped, meaning fields is empty upon editing an employee (this might mean we have to redevelop how we edit employees to work around the hashed passwords)

Pushed the fix.

**Review by JohannGon118 — APPROVED** [review]

**Pull request merged**
